version: '3.4'
services:
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    container_name: homebuh_php
    volumes:
      - ./source/app:/srv/www/homebuh
    expose:
      - 9000
    depends_on:
      - "mysql"
    environment:
      - MYSQL_HOST=mysql

  nginx:
    build:
      context: ./docker/nginx
    container_name: homebuh_nginx
    command: bash -c "exec nginx -g 'daemon off;'"
    volumes:
      - ./source/app:/srv/www/homebuh
    working_dir: /srv/www/homebuh
    ports:
      - 82:80
    depends_on:
      - "php-fpm"
  mysql:
    container_name: homebuh_mysql
    image: percona/percona-server:5.7
    env_file: ./source/app/.env
    command: "--default-authentication-plugin=mysql_native_password --disable-log-bin"
    volumes:
      - homebuh-mysql:/var/lib/mysql
    ports:
    - 3308:3306
    user: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

volumes:
  homebuh-mysql: